#!/bin/bash
# EC2 User Data — runs ONCE on first instance launch.
# Installs packages, sets up the system, fetches secrets from Secrets Manager.
# CodeDeploy handles all subsequent deploys.

set -euo pipefail
exec > >(tee /var/log/eatpulse-userdata.log | logger -t eatpulse-userdata -s 2>/dev/console) 2>&1

SECRET_ID="${1:-eatpulse/prod}"
ENVIRONMENT="${2:-prod}"
APP_DIR="/opt/eatpulse"
APP_USER="eatpulse"

echo "=== EatPulse bootstrap started ==="
echo "Secret ID: $SECRET_ID | Environment: $ENVIRONMENT"

# ── System packages ────────────────────────────────────────────────────────────
dnf update -y
dnf install -y \
    python3.11 python3.11-pip python3.11-devel \
    nginx \
    postgresql15 \
    pgbouncer \
    git \
    jq \
    unzip \
    gcc gcc-c++ make

# AWS CodeDeploy agent
dnf install -y ruby wget
wget -q "https://aws-codedeploy-ap-south-1.s3.ap-south-1.amazonaws.com/latest/install" -O /tmp/codedeploy-install
chmod +x /tmp/codedeploy-install
/tmp/codedeploy-install auto
systemctl enable --now codedeploy-agent

# ── App user & directories ────────────────────────────────────────────────────
id -u $APP_USER &>/dev/null || useradd --system --no-create-home --shell /sbin/nologin $APP_USER
mkdir -p $APP_DIR
chown $APP_USER:$APP_USER $APP_DIR

# Python venv
python3.11 -m venv $APP_DIR/venv
chown -R $APP_USER:$APP_USER $APP_DIR/venv

# ── Fetch secrets from Secrets Manager ────────────────────────────────────────
echo "Fetching secrets from Secrets Manager..."
REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
SECRETS=$(aws secretsmanager get-secret-value \
    --region "$REGION" \
    --secret-id "$SECRET_ID" \
    --query SecretString \
    --output text)

# Write .env file
cat > $APP_DIR/.env <<EOF
# Generated by userdata.sh at $(date -u)
AWS_SECRETS_MANAGER_SECRET_ID=$SECRET_ID
AWS_REGION=$REGION
ENVIRONMENT=$ENVIRONMENT
EOF

# Append all secrets as env vars
echo "$SECRETS" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $APP_DIR/.env
chmod 600 $APP_DIR/.env
chown $APP_USER:$APP_USER $APP_DIR/.env

# Extract DB password and Aurora endpoint for PgBouncer config
DB_PASSWORD=$(echo "$SECRETS" | jq -r '.DB_PASSWORD // empty')

# ── Nginx ──────────────────────────────────────────────────────────────────────
mkdir -p /etc/nginx/sites-enabled
cat > /etc/nginx/sites-enabled/eatpulse <<'NGINX_CONF'
server {
    listen 80;
    server_name _;

    location = /health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }

    location / {
        proxy_pass         http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout  60s;
        client_max_body_size 10M;
    }
}
NGINX_CONF

# Remove default nginx config that blocks our setup
rm -f /etc/nginx/conf.d/default.conf
# Include our sites-enabled
echo 'include /etc/nginx/sites-enabled/*;' >> /etc/nginx/nginx.conf

systemctl enable --now nginx

# ── PgBouncer ──────────────────────────────────────────────────────────────────
mkdir -p /var/log/pgbouncer /var/run/pgbouncer
chown pgbouncer:pgbouncer /var/log/pgbouncer /var/run/pgbouncer || true

# PgBouncer config will be updated by install_dependencies.sh with the real Aurora endpoint.
# Write a placeholder now so pgbouncer starts:
cat > /etc/pgbouncer/pgbouncer.ini <<'PGBOUNCER_CONF'
[databases]
eatpulse = host=127.0.0.1 port=5432 dbname=eatpulse

[pgbouncer]
listen_addr     = 127.0.0.1
listen_port     = 5432
auth_type       = scram-sha-256
auth_file       = /etc/pgbouncer/userlist.txt
pool_mode       = transaction
max_client_conn = 100
default_pool_size = 10
server_idle_timeout = 300
log_connections = 0
log_disconnections = 0
PGBOUNCER_CONF

# PgBouncer user list placeholder — updated at deploy time
cat > /etc/pgbouncer/userlist.txt <<EOF
"eatpulse" "placeholder"
EOF
chmod 600 /etc/pgbouncer/userlist.txt

# ── Systemd service for EatPulse API ─────────────────────────────────────────
cat > /etc/systemd/system/eatpulse-api.service <<EOF
[Unit]
Description=EatPulse FastAPI + Telegram Bot
After=network.target pgbouncer.service
Requires=pgbouncer.service

[Service]
Type=exec
User=$APP_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
ExecStart=$APP_DIR/venv/bin/uvicorn dashboard.api.app:create_app \\
    --factory \\
    --host 127.0.0.1 \\
    --port 8000 \\
    --workers 2 \\
    --access-log \\
    --log-level info
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=eatpulse-api

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable eatpulse-api
# Don't start yet — CodeDeploy will do the first deploy

echo "=== EatPulse bootstrap complete ==="
