"""ConversationHandler state constants."""

# Onboarding states
ONBOARDING_NAME = "ONBOARDING_NAME"
ONBOARDING_CITY = "ONBOARDING_CITY"
ONBOARDING_PINCODE = "ONBOARDING_PINCODE"
ONBOARDING_DIET = "ONBOARDING_DIET"
ONBOARDING_TIMEZONE = "ONBOARDING_TIMEZONE"

# Suggestion flow states
SUGGEST_HEALTH = "SUGGEST_HEALTH"
SUGGEST_METHOD = "SUGGEST_METHOD"
SUGGEST_EAT_IN = "SUGGEST_EAT_IN"
SUGGEST_SOURCE = "SUGGEST_SOURCE"
SUGGEST_SWIGGY_PHONE = "SUGGEST_SWIGGY_PHONE"
SUGGEST_SWIGGY_OTP = "SUGGEST_SWIGGY_OTP"
